apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-web.fullname" . }}-content
  labels:
    {{- include "hello-web.labels" . | nindent 4 }}
data:
  index.html: |
{{ .Values.content.indexHtml | indent 4 }}
